pipeline {
    agent any

    environment {
        COMPOSE_PROJECT_NAME = "forseva"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/SujalSawant-97/ForSeva-.git'
            }
        }

        stage('Build Spring Boot JARs') {
            steps {
                dir('ForSeva Backend') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                dir('ForSeva Backend') {
                    sh 'docker-compose build'
                }
            }
        }

        stage('Deploy Containers') {
            steps {
                dir('ForSeva Backend') {
                    sh 'docker-compose down'
                    sh 'docker-compose up -d'
                }
            }
        }
    }

    post {
        success {
            echo '✅ Deployment successful!'
        }
        failure {
            echo '❌ Deployment failed. Check logs.'
        }
    }
}
