pipeline {
    agent any

    tools {
            jdk 'jdk-21'
            maven 'maven-3'
        }

    options {
            timestamps()
            disableConcurrentBuilds()
        }

    environment {
        COMPOSE_PROJECT_NAME = "forseva"
    }

    stages {

        stage('Checkout Code') {
             steps {
                 echo 'Checking out source code...'
                        checkout scm
                 }
             }

        stage('Verify Tools') {
            steps {
                 sh 'java -version'
                 sh 'mvn -version'
                 sh 'docker --version'
                 sh 'docker-compose --version'
                }
            }

        stage('Build Spring Boot JARs') {
            steps {
                dir('ForSeva Backend') {
                    echo 'Building all Spring Boot services...'
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                dir('ForSeva Backend') {
                    echo 'Building Docker images...'
                     sh 'docker-compose build'
                }
            }
        }

        stage('Deploy Containers') {
            steps {
                dir('ForSeva Backend') {
                    echo 'Deploying containers...'
                    sh 'docker-compose down || true'
                    sh 'docker-compose up -d'
                }
            }
        }
    }

    post {
        success {
            echo '✅ Deployment successful!'
        }
        failure {
            echo '❌ Deployment failed. Check logs.'
        }
    }
}
